
// This file has been generated by the GUI designer. Do not modify.
namespace cubectl
{
	public partial class widget_none
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget cubectl.widget_none
			global::Stetic.BinContainer.Attach (this);
			this.Name = "cubectl.widget_none";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
