
// This file has been generated by the GUI designer. Do not modify.
namespace cubectl
{
	public partial class widget_console
	{
		private global::Gtk.Notebook notebook_console;
		private global::Gtk.VBox vbox2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView textview_sermon;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button bt_sersend;
		private global::Gtk.Entry entry_sersend;
		private global::Gtk.Label label1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textview_errors;
		private global::Gtk.Label label2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget cubectl.widget_console
			global::Stetic.BinContainer.Attach (this);
			this.Name = "cubectl.widget_console";
			// Container child cubectl.widget_console.Gtk.Container+ContainerChild
			this.notebook_console = new global::Gtk.Notebook ();
			this.notebook_console.CanFocus = true;
			this.notebook_console.Name = "notebook_console";
			this.notebook_console.CurrentPage = 0;
			this.notebook_console.TabPos = ((global::Gtk.PositionType)(0));
			// Container child notebook_console.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview_sermon = new global::Gtk.TextView ();
			this.textview_sermon.CanFocus = true;
			this.textview_sermon.Name = "textview_sermon";
			this.textview_sermon.Editable = false;
			this.textview_sermon.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add (this.textview_sermon);
			this.vbox2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow1]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.bt_sersend = new global::Gtk.Button ();
			this.bt_sersend.CanFocus = true;
			this.bt_sersend.Name = "bt_sersend";
			this.bt_sersend.UseUnderline = true;
			// Container child bt_sersend.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-yes", global::Gtk.IconSize.Button);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Senden");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.bt_sersend.Add (w3);
			this.hbox3.Add (this.bt_sersend);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.bt_sersend]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entry_sersend = new global::Gtk.Entry ();
			this.entry_sersend.CanFocus = true;
			this.entry_sersend.Name = "entry_sersend";
			this.entry_sersend.IsEditable = true;
			this.entry_sersend.InvisibleChar = '●';
			this.hbox3.Add (this.entry_sersend);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entry_sersend]));
			w12.Position = 1;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.notebook_console.Add (this.vbox2);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("SerialMon");
			this.notebook_console.SetTabLabel (this.vbox2, this.label1);
			this.label1.ShowAll ();
			// Container child notebook_console.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview_errors = new global::Gtk.TextView ();
			this.textview_errors.CanFocus = true;
			this.textview_errors.Name = "textview_errors";
			this.textview_errors.Editable = false;
			this.GtkScrolledWindow.Add (this.textview_errors);
			this.notebook_console.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w16 = ((global::Gtk.Notebook.NotebookChild)(this.notebook_console [this.GtkScrolledWindow]));
			w16.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("errors");
			this.notebook_console.SetTabLabel (this.GtkScrolledWindow, this.label2);
			this.label2.ShowAll ();
			this.Add (this.notebook_console);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.bt_sersend.Activated += new global::System.EventHandler (this.OnBtSersendActivated);
			this.bt_sersend.Clicked += new global::System.EventHandler (this.OnBtSersendClicked);
		}
	}
}
