
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action SerialPortsAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.HBox hbox_home;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView home_treeview_effects;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::cubectl.widget_console widget_console1;
	private global::Gtk.Label label3;
	private global::Gtk.Statusbar statusbar1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.SerialPortsAction = new global::Gtk.Action ("SerialPortsAction", global::Mono.Unix.Catalog.GetString ("Serial Ports"), null, null);
		this.SerialPortsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Serial Ports");
		w1.Add (this.SerialPortsAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'FileAction\' action=\'FileAction\'/><menu n" +
				"ame=\'SerialPortsAction\' action=\'SerialPortsAction\'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 2;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox_home = new global::Gtk.HBox ();
		this.hbox_home.Name = "hbox_home";
		this.hbox_home.Spacing = 6;
		// Container child hbox_home.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.home_treeview_effects = new global::Gtk.TreeView ();
		this.home_treeview_effects.CanFocus = true;
		this.home_treeview_effects.Name = "home_treeview_effects";
		this.GtkScrolledWindow.Add (this.home_treeview_effects);
		this.hbox_home.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox_home [this.GtkScrolledWindow]));
		w4.Position = 0;
		this.notebook1.Add (this.hbox_home);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("home");
		this.notebook1.SetTabLabel (this.hbox_home, this.label1);
		this.label1.ShowAll ();
		// Notebook tab
		global::Gtk.Label w6 = new global::Gtk.Label ();
		w6.Visible = true;
		this.notebook1.Add (w6);
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("analysis");
		this.notebook1.SetTabLabel (w6, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.widget_console1 = new global::cubectl.widget_console ();
		this.widget_console1.Events = ((global::Gdk.EventMask)(256));
		this.widget_console1.Name = "widget_console1";
		this.notebook1.Add (this.widget_console1);
		global::Gtk.Notebook.NotebookChild w7 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.widget_console1]));
		w7.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("console");
		this.notebook1.SetTabLabel (this.widget_console1, this.label3);
		this.label3.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w8.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 439;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SerialPortsAction.Activated += new global::System.EventHandler (this.OnSerialPortsActionActivated);
		this.home_treeview_effects.CursorChanged += new global::System.EventHandler (this.OnHomeTreeviewEffectsCursorChanged);
	}
}
